#![allow(dead_code)] // Functions used by future sot_generator module

use crate::models::{Delta, Override, Template};

/// Generate the file-level header banner.
///
/// Returns exactly 4 lines: two separator lines framing the title and
/// generation-source metadata. No indentation — these go at level 0.
pub fn generate_file_header(templates_name: &str, agents_name: &str) -> Vec<String> {
    let sep = format!("// {}", "=".repeat(77));
    vec![
        sep.clone(),
        "// OpenCode Agent Permissions \u{2014} Source of Truth".to_string(),
        format!(
            "// Generated by agency from {}/ + {}/",
            templates_name, agents_name
        ),
        sep,
    ]
}

/// Generate the category separator/header block from template metadata.
///
/// Produces a `// ====...====` banner with the category name, the template's
/// `description` field, and optional `$doc.baseline_rationale` /
/// `$doc.security_note` lines. All descriptive text comes from the template.
/// Returns lines WITHOUT indentation (caller adds indent).
pub fn generate_category_header(
    template: &Template,
    parent_names: Option<&[String]>,
) -> Vec<String> {
    let sep = format!("// {}", "=".repeat(73));
    let mut lines = Vec::new();

    lines.push(sep.clone());
    lines.push(format!("// Category: {}", template.category));
    if let Some(parents) = parent_names {
        if !parents.is_empty() {
            lines.push(format!("// Inherits: {}", parents.join(", ")));
        }
    }
    lines.push(format!("// {}", template.description));

    if let Some(ref doc) = template.doc {
        if let Some(ref rationale) = doc.baseline_rationale {
            lines.push(format!("// Baseline: {}", rationale));
        }
        if let Some(ref note) = doc.security_note {
            lines.push(format!("// Security: {}", note));
        }
    }

    lines.push(sep);
    lines
}

/// Generate the per-agent comment block from override metadata,
/// template context, and delta.
///
/// Produces `// --- agent-name ---` followed by a summary line (from
/// `$doc.agent_summary` or falling back to `template.description`),
/// an overrides delta summary, and an optional rationale line.
/// Returns lines WITHOUT indentation (caller adds indent).
pub fn generate_agent_header(
    override_data: &Override,
    template: &Template,
    delta: &Delta,
) -> Vec<String> {
    let mut lines = Vec::new();

    lines.push(format!("// --- {} ---", override_data.agent));

    // Summary: prefer override $doc.agent_summary, fall back to template description
    let summary = override_data
        .doc
        .as_ref()
        .and_then(|d| d.agent_summary.as_deref())
        .unwrap_or(&template.description);
    lines.push(format!("// {}", summary));

    // Overrides delta summary
    lines.push(format!("// Overrides: {}", format_delta_summary(delta)));

    // Optional rationale from override $doc
    if let Some(ref doc) = override_data.doc {
        if let Some(ref rationale) = doc.override_rationale {
            lines.push(format!("// Rationale: {}", rationale));
        }
    }

    lines
}

/// Format a delta into a human-readable summary string.
///
/// Examples:
/// - Zero delta: `"none (matches baseline exactly)"`
/// - Adds only: `"+4 adds (next *, playwright *, turbo *, docker *)"`
/// - Removes only: `"-2 removes (git log, git status)"`
/// - Both: `"+3 adds (next *, turbo *, docker *), -1 remove (git log)"`
/// - Many (>5): `"+8 adds (npm *, npx *, pnpm *, bun *, ...)"`
fn format_delta_summary(delta: &Delta) -> String {
    let has_adds = !delta.adds.is_empty();
    let has_removes = !delta.removes.is_empty();

    if !has_adds && !has_removes {
        return "none (matches baseline exactly)".to_string();
    }

    let mut parts = Vec::new();

    if has_adds {
        let count = delta.adds.len();
        let noun = if count == 1 { "add" } else { "adds" };
        let keys = format_key_list(delta.adds.iter().map(|(k, _)| k.as_str()), count);
        parts.push(format!("+{} {} ({})", count, noun, keys));
    }

    if has_removes {
        let count = delta.removes.len();
        let noun = if count == 1 { "remove" } else { "removes" };
        let keys = format_key_list(delta.removes.iter().map(|k| k.as_str()), count);
        parts.push(format!("-{} {} ({})", count, noun, keys));
    }

    parts.join(", ")
}

/// Format a list of key names, truncating if more than 5.
/// Shows first 4 keys + "..." when truncated.
fn format_key_list<'a>(keys: impl Iterator<Item = &'a str>, total: usize) -> String {
    if total > 5 {
        let shown: Vec<&str> = keys.take(4).collect();
        format!("{}, ...", shown.join(", "))
    } else {
        let shown: Vec<&str> = keys.collect();
        shown.join(", ")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::*;

    fn make_template(category: &str, description: &str, doc: Option<DocBlock>) -> Template {
        Template {
            schema: "https://raw.githubusercontent.com/nmindz/agency/master/schemas/template.json"
                .to_string(),
            version: "1.1.0".to_string(),
            category: category.to_string(),
            description: description.to_string(),
            purpose: "test purpose".to_string(),
            doc,
            extends: None,
            baseline: TemplateBaseline {
                permission: serde_json::json!({"bash": "deny"}),
            },
        }
    }

    fn make_override(agent: &str, _extends: &str, doc: Option<DocBlock>) -> Override {
        Override {
            schema: "https://raw.githubusercontent.com/nmindz/agency/master/schemas/agent.json"
                .to_string(),
            version: "1.1.0".to_string(),
            agent: agent.to_string(),
            extends: _extends.to_string(),
            doc,
            overrides: OverrideBlock::default(),
        }
    }

    fn make_delta(adds: Vec<(&str, &str)>, removes: Vec<&str>) -> Delta {
        Delta {
            adds: adds
                .into_iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
            removes: removes.into_iter().map(|s| s.to_string()).collect(),
        }
    }

    // -----------------------------------------------------------------------
    // 1. test_file_header
    // -----------------------------------------------------------------------
    #[test]
    fn test_file_header() {
        let lines = generate_file_header("_templates", "_agents");
        assert_eq!(lines.len(), 4, "file header must have exactly 4 lines");
        // First and last lines are separators
        assert!(lines[0].starts_with("// ==="));
        assert!(lines[3].starts_with("// ==="));
        assert_eq!(lines[0], lines[3], "separators must match");
        // Title and generation info
        assert!(lines[1].contains("OpenCode Agent Permissions"));
        assert!(lines[2].contains("Generated by agency"));
        assert!(lines[2].contains("_templates/"));
        assert!(lines[2].contains("_agents/"));
    }

    // -----------------------------------------------------------------------
    // 2. test_category_header_with_doc
    // -----------------------------------------------------------------------
    #[test]
    fn test_category_header_with_doc() {
        let doc = DocBlock {
            baseline_rationale: Some("Standard backend toolchain".to_string()),
            security_note: Some("Docker excluded from baseline".to_string()),
            ..Default::default()
        };
        let template = make_template("backend-api", "Backend specialist agents", Some(doc));
        let lines = generate_category_header(&template, None);

        // Should have: sep, category, description, baseline, security, sep = 6 lines
        assert_eq!(lines.len(), 6);
        assert!(lines[0].starts_with("// ==="));
        assert!(lines[1].contains("Category: backend-api"));
        assert!(lines[2].contains("Backend specialist agents"));
        assert!(lines[3].contains("Baseline: Standard backend toolchain"));
        assert!(lines[4].contains("Security: Docker excluded from baseline"));
        assert!(lines[5].starts_with("// ==="));
    }

    // -----------------------------------------------------------------------
    // 3. test_category_header_without_doc
    // -----------------------------------------------------------------------
    #[test]
    fn test_category_header_without_doc() {
        let template = make_template("planning", "Planning agents", None);
        let lines = generate_category_header(&template, None);

        // Should have: sep, category, description, sep = 4 lines
        assert_eq!(lines.len(), 4);
        assert!(lines[1].contains("Category: planning"));
        assert!(lines[2].contains("Planning agents"));
        // No baseline or security lines
        for line in &lines {
            assert!(!line.contains("Baseline:"));
            assert!(!line.contains("Security:"));
        }
    }

    // -----------------------------------------------------------------------
    // 4. test_category_header_partial_doc
    // -----------------------------------------------------------------------
    #[test]
    fn test_category_header_partial_doc() {
        let doc = DocBlock {
            baseline_rationale: Some("Standard toolchain".to_string()),
            security_note: None,
            ..Default::default()
        };
        let template = make_template("backend-api", "Backend agents", Some(doc));
        let lines = generate_category_header(&template, None);

        // Should have: sep, category, description, baseline, sep = 5 lines
        assert_eq!(lines.len(), 5);
        assert!(lines[3].contains("Baseline: Standard toolchain"));
        for line in &lines {
            assert!(!line.contains("Security:"));
        }
    }

    // -----------------------------------------------------------------------
    // 5. test_agent_header_with_full_doc
    // -----------------------------------------------------------------------
    #[test]
    fn test_agent_header_with_full_doc() {
        let doc = DocBlock {
            agent_summary: Some("Backend APIs, Prisma, PostgreSQL".to_string()),
            override_rationale: Some("Adds Next.js and Docker".to_string()),
            ..Default::default()
        };
        let ov = make_override("x-backend-engineer", "backend-api", Some(doc));
        let template = make_template("backend-api", "Backend agents", None);
        let delta = make_delta(vec![("next *", "allow"), ("docker *", "allow")], vec![]);
        let lines = generate_agent_header(&ov, &template, &delta);

        assert_eq!(lines.len(), 4);
        assert!(lines[0].contains("--- x-backend-engineer ---"));
        assert!(lines[1].contains("Backend APIs, Prisma, PostgreSQL"));
        assert!(lines[2].contains("Overrides: +2 adds"));
        assert!(lines[3].contains("Rationale: Adds Next.js and Docker"));
    }

    // -----------------------------------------------------------------------
    // 6. test_agent_header_without_doc
    // -----------------------------------------------------------------------
    #[test]
    fn test_agent_header_without_doc() {
        let ov = make_override("plan", "planning", None);
        let template = make_template("planning", "Planning and analysis agents", None);
        let delta = make_delta(vec![], vec![]);
        let lines = generate_agent_header(&ov, &template, &delta);

        assert_eq!(lines.len(), 3);
        assert!(lines[0].contains("--- plan ---"));
        // Falls back to template.description
        assert!(lines[1].contains("Planning and analysis agents"));
        assert!(lines[2].contains("none (matches baseline exactly)"));
    }

    // -----------------------------------------------------------------------
    // 7. test_agent_header_zero_delta
    // -----------------------------------------------------------------------
    #[test]
    fn test_agent_header_zero_delta() {
        let ov = make_override("plan", "planning", None);
        let template = make_template("planning", "Planning agents", None);
        let delta = make_delta(vec![], vec![]);
        let lines = generate_agent_header(&ov, &template, &delta);

        assert!(lines
            .iter()
            .any(|l| l.contains("none (matches baseline exactly)")));
    }

    // -----------------------------------------------------------------------
    // 8. test_agent_header_adds_only
    // -----------------------------------------------------------------------
    #[test]
    fn test_agent_header_adds_only() {
        let ov = make_override("x-backend-engineer", "backend-api", None);
        let template = make_template("backend-api", "Backend agents", None);
        let delta = make_delta(
            vec![
                ("next *", "allow"),
                ("playwright *", "allow"),
                ("turbo *", "allow"),
                ("docker *", "allow"),
            ],
            vec![],
        );
        let lines = generate_agent_header(&ov, &template, &delta);

        let overrides_line = lines.iter().find(|l| l.contains("Overrides:")).unwrap();
        assert!(overrides_line.contains("+4 adds"));
        assert!(overrides_line.contains("next *"));
        assert!(overrides_line.contains("playwright *"));
        assert!(overrides_line.contains("turbo *"));
        assert!(overrides_line.contains("docker *"));
    }

    // -----------------------------------------------------------------------
    // 9. test_agent_header_removes_only
    // -----------------------------------------------------------------------
    #[test]
    fn test_agent_header_removes_only() {
        let ov = make_override("restricted-agent", "backend-api", None);
        let template = make_template("backend-api", "Backend agents", None);
        let delta = make_delta(vec![], vec!["git log", "git status"]);
        let lines = generate_agent_header(&ov, &template, &delta);

        let overrides_line = lines.iter().find(|l| l.contains("Overrides:")).unwrap();
        assert!(overrides_line.contains("-2 removes"));
        assert!(overrides_line.contains("git log"));
        assert!(overrides_line.contains("git status"));
    }

    // -----------------------------------------------------------------------
    // 10. test_agent_header_adds_and_removes
    // -----------------------------------------------------------------------
    #[test]
    fn test_agent_header_adds_and_removes() {
        let ov = make_override("mixed-agent", "backend-api", None);
        let template = make_template("backend-api", "Backend agents", None);
        let delta = make_delta(
            vec![
                ("next *", "allow"),
                ("turbo *", "allow"),
                ("docker *", "allow"),
            ],
            vec!["git log"],
        );
        let lines = generate_agent_header(&ov, &template, &delta);

        let overrides_line = lines.iter().find(|l| l.contains("Overrides:")).unwrap();
        assert!(overrides_line.contains("+3 adds"));
        assert!(overrides_line.contains("-1 remove"));
        // Singular "remove" for count=1
        assert!(!overrides_line.contains("removes"));
    }

    // -----------------------------------------------------------------------
    // 11. test_agent_header_many_adds_truncated
    // -----------------------------------------------------------------------
    #[test]
    fn test_agent_header_many_adds_truncated() {
        let ov = make_override("heavy-agent", "backend-api", None);
        let template = make_template("backend-api", "Backend agents", None);
        let delta = make_delta(
            vec![
                ("npm *", "allow"),
                ("npx *", "allow"),
                ("pnpm *", "allow"),
                ("bun *", "allow"),
                ("yarn *", "allow"),
                ("node *", "allow"),
                ("next *", "allow"),
                ("turbo *", "allow"),
            ],
            vec![],
        );
        let lines = generate_agent_header(&ov, &template, &delta);

        let overrides_line = lines.iter().find(|l| l.contains("Overrides:")).unwrap();
        assert!(overrides_line.contains("+8 adds"));
        // Shows first 4 keys + "..."
        assert!(overrides_line.contains("npm *"));
        assert!(overrides_line.contains("npx *"));
        assert!(overrides_line.contains("pnpm *"));
        assert!(overrides_line.contains("bun *"));
        assert!(overrides_line.contains("..."));
        // Should NOT contain the 5th+ keys
        assert!(!overrides_line.contains("yarn *"));
        assert!(!overrides_line.contains("node *"));
    }

    // -----------------------------------------------------------------------
    // 12. test_delta_summary_singular
    // -----------------------------------------------------------------------
    #[test]
    fn test_delta_summary_singular() {
        let delta = make_delta(vec![("docker *", "allow")], vec![]);
        let summary = format_delta_summary(&delta);
        assert_eq!(summary, "+1 add (docker *)");

        let delta = make_delta(vec![], vec!["git log"]);
        let summary = format_delta_summary(&delta);
        assert_eq!(summary, "-1 remove (git log)");
    }

    // -----------------------------------------------------------------------
    // 13. test_no_hardcoded_content — proves output is data-driven
    // -----------------------------------------------------------------------
    #[test]
    fn test_no_hardcoded_content() {
        let doc_a = DocBlock {
            agent_summary: Some("Summary Alpha".to_string()),
            override_rationale: Some("Rationale Alpha".to_string()),
            ..Default::default()
        };
        let doc_b = DocBlock {
            agent_summary: Some("Summary Beta".to_string()),
            override_rationale: Some("Rationale Beta".to_string()),
            ..Default::default()
        };

        let template = make_template("cat-x", "Description X", None);
        let delta = make_delta(vec![], vec![]);

        let ov_a = make_override("agent-a", "cat-x", Some(doc_a));
        let lines_a = generate_agent_header(&ov_a, &template, &delta);

        let ov_b = make_override("agent-b", "cat-x", Some(doc_b));
        let lines_b = generate_agent_header(&ov_b, &template, &delta);

        // Different doc fields → different output (proves data-driven)
        assert_ne!(lines_a, lines_b);
        assert!(lines_a.iter().any(|l| l.contains("Summary Alpha")));
        assert!(lines_b.iter().any(|l| l.contains("Summary Beta")));
        assert!(lines_a.iter().any(|l| l.contains("Rationale Alpha")));
        assert!(lines_b.iter().any(|l| l.contains("Rationale Beta")));

        // Also verify category header is data-driven
        let cat_doc = DocBlock {
            baseline_rationale: Some("Custom rationale".to_string()),
            ..Default::default()
        };
        let template_1 = make_template("custom-cat", "Custom description", Some(cat_doc));
        let cat_lines = generate_category_header(&template_1, None);
        assert!(cat_lines.iter().any(|l| l.contains("Custom description")));
        assert!(cat_lines.iter().any(|l| l.contains("Custom rationale")));
    }

    #[test]
    fn test_category_header_with_parents() {
        let template = make_template("backend-api", "Backend specialist agents", None);
        let parents = vec!["vcs-permissions".to_string()];
        let lines = generate_category_header(&template, Some(&parents));
        assert!(lines
            .iter()
            .any(|l| l.contains("Inherits: vcs-permissions")));
        assert!(lines.iter().any(|l| l.contains("Category: backend-api")));
    }

    #[test]
    fn test_category_header_multiple_parents() {
        let template = make_template("backend-api", "Backend agents", None);
        let parents = vec!["vcs-permissions".to_string(), "node-toolchain".to_string()];
        let lines = generate_category_header(&template, Some(&parents));
        assert!(lines
            .iter()
            .any(|l| l.contains("Inherits: vcs-permissions, node-toolchain")));
    }

    #[test]
    fn test_category_header_no_parents() {
        let template = make_template("orchestration", "Orchestration agents", None);
        let lines = generate_category_header(&template, None);
        assert!(!lines.iter().any(|l| l.contains("Inherits:")));
    }

    #[test]
    fn test_category_header_empty_parents() {
        let template = make_template("orchestration", "Orchestration agents", None);
        let empty: Vec<String> = vec![];
        let lines = generate_category_header(&template, Some(&empty));
        assert!(!lines.iter().any(|l| l.contains("Inherits:")));
    }
}
